version: '3'
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "13579:13579"
      - "13580:13580"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --address ":13579" --console-address ":13580"

volumes:
  minio_data:
    driver: local
